# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(140, 200, 75, 23))
        self.button_submit.setObjectName("button_submit")
        self.vote_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.vote_id.setGeometry(QtCore.QRect(130, 60, 113, 20))
        self.vote_id.setObjectName("vote_id")
        self.id = QtWidgets.QLabel(parent=self.centralwidget)
        self.id.setGeometry(QtCore.QRect(110, 60, 21, 16))
        self.id.setObjectName("id")
        self.vote_app = QtWidgets.QLabel(parent=self.centralwidget)
        self.vote_app.setGeometry(QtCore.QRect(130, 10, 121, 16))
        self.vote_app.setObjectName("vote_app")
        self.candidates = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidates.setGeometry(QtCore.QRect(150, 90, 71, 16))
        self.candidates.setObjectName("candidates")
        self.jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.jane.setGeometry(QtCore.QRect(150, 130, 82, 17))
        self.jane.setObjectName("jane")
        self.john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.john.setGeometry(QtCore.QRect(150, 160, 82, 17))
        self.john.setObjectName("john")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GUI_PyQt"))
        self.button_submit.setText(_translate("MainWindow", "Vote"))
        self.id.setText(_translate("MainWindow", "ID"))
        self.vote_app.setText(_translate("MainWindow", "VOTING APPLICATION"))
        self.candidates.setText(_translate("MainWindow", "CANDIDATES"))
        self.jane.setText(_translate("MainWindow", "Jane"))
        self.john.setText(_translate("MainWindow", "John"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
